// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVttfX-_DP16qvMixQgPsYs0gKN6yhHs',
    appId: '1:406644175740:android:7f488d6dbb1948b6972af9',
    messagingSenderId: '406644175740',
    projectId: 'fir-witheyad1',
    databaseURL: 'https://fir-witheyad1.firebaseio.com',
    storageBucket: 'fir-witheyad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkodg6FOYGwg_I1EIgUSt_e0-CN3uD99E',
    appId: '1:406644175740:ios:f3a344246f5989a9972af9',
    messagingSenderId: '406644175740',
    projectId: 'fir-witheyad1',
    databaseURL: 'https://fir-witheyad1.firebaseio.com',
    storageBucket: 'fir-witheyad1.appspot.com',
    iosClientId: '406644175740-3s1umirr0u2s8s0pg7ue3b6k7sfgiimp.apps.googleusercontent.com',
    iosBundleId: 'com.example.expectations',
  );
}
